### ISSUE TITLE
pip warning about versioning deprecation

### ISSUE THREAD

**Issue by iamtherobin** [vapoursynth/vs-imwri#10]
>DEPRECATION: imagemagick-writer Reader-IMWRI has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of imagemagick-writer or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

pip 24.1 milestone is due by august 2024.

**Comment by myrsloik** [comment]
Issue spammer with bullshit on top
